# Generated by Django 3.1.7 on 2021-05-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Table',
        ),
    ]
