# Generated by Django 3.1.7 on 2021-05-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20210518_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
    ]
