# Generated by Django 3.1.7 on 2021-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
