# Generated by Django 3.1.7 on 2021-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monan', '0004_auto_20210518_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
