# Generated by Django 3.1.7 on 2021-05-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monan', '0006_auto_20210518_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
