# Generated by Django 3.1.7 on 2021-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monan', '0008_auto_20210526_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
