# Generated by Django 3.1.7 on 2021-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monan', '0009_auto_20210526_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
