# Generated by Django 3.1.7 on 2021-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210528_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
