# Generated by Django 3.1.7 on 2021-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../media/profile.jpg', upload_to='../media/'),
        ),
    ]
